### ISSUE TITLE
Not work blender 2.78

### ISSUE THREAD

**Issue by Durman** [heikkisa/blender-import-sketchup#1]
![2017-10-24_10-53-33](https://user-images.githubusercontent.com/28003269/31928561-a6c89762-b8a9-11e7-980b-141d085f12f0.png)

**Comment by vranki** [comment]
Works here, Blender 2.78 on Ubuntu 17.10.

**Comment by Durman** [comment]
Maybe it doesn't work with Windows only. :/

**Comment by ProgGrog** [comment]
1) It worked here.  Using Win 10, Blender 2.78.  Sketchup Make 2017 export to Collada dae
2) Note: installation from the zip failed, but extracting the .py, installation from the .py worked.

3) Also, by "worked", I do mean to say Sketchup included a few messed up normals, and some orphan geometry.  But the scale and textures and orientation were correct.
